/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NewsApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NewsCollector": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}